//! Flat semantic reference index (spec §38, §188-189): the gold recall
//! baseline every approximate index (TQVec, Phase 39+) is measured
//! against. "Before custom ANN, implement exact SIMD search over the
//! compact/reference vector store." This phase's search is a plain
//! auto-vectorizable scalar Rust loop, not hand-written SIMD intrinsics
//! — a REFERENCE BASELINE tier, matching how `model::qwen36`'s own
//! full-attention started scalar before later phases added real NEON/
//! Metal kernels; a hand-tuned kernel is only worth writing once this
//! baseline's cost is actually shown to matter.
//!
//! Reference controls implemented (spec §189):
//! 1. FP32 1024-d cosine/dot (the checkpoint's own output is F32, not
//!    F16 — spec's "FP16... cosine/dot" intent is "full precision",
//!    which this crate already carries as F32 throughout);
//! 2. INT8 1024-d dot with a per-vector linear scale (distinct from
//!    Phase 37's model-native tanh-INT8 compact output: that one has no
//!    stored scale by design, per the checkpoint's own
//!    `st_quantize.py`; this is the spec's separate "quantize the
//!    reference vector" control, computed at index-build time);
//! 3. native binary/Hamming (reusing the model's own sign-based compact
//!    binary output from Phase 37, since it *is* "available" here,
//!    satisfying spec's "where available").
//!
//! Plus spec §188's MRL prefixes at 256/512, generated by truncating the
//! normalized full embedding and re-normalizing.

use crate::error::Result;
use crate::helper_model::PplxEmbedRuntime;

/// One document's full reference representation. `fp32` is the
/// canonical L2-normalized 1024-d embedding (spec §188); everything
/// else is a compact control derived from it at build time.
#[derive(Debug, Clone)]
pub struct FlatRecord {
    pub id: String,
    pub fp32: Vec<f32>,
    pub int8: Vec<i8>,
    pub int8_scale: f32,
    /// Sign-based packed binary (MSB-first, 8 dims/byte) — the model's
    /// own native compact output, not a separately learned binary head.
    pub binary_packed: Vec<u8>,
}

#[derive(Debug, Default)]
pub struct FlatVectorStore {
    pub records: Vec<FlatRecord>,
}

pub fn l2_normalize(values: &mut [f32]) {
    let norm = values.iter().map(|v| v * v).sum::<f32>().sqrt();
    if norm > 0.0 {
        for v in values.iter_mut() {
            *v /= norm;
        }
    }
}

/// Symmetric per-vector linear INT8 quantization (spec §189 control 2):
/// `scale = max(|x|) / 127`, `q_i = round(x_i / scale)` clamped to
/// `i8::MIN+1..=i8::MAX` so `-scale*127` and `scale*127` are the true
/// representable extremes in both directions.
pub fn quantize_int8_linear(values: &[f32]) -> (Vec<i8>, f32) {
    let max_abs = values.iter().fold(0.0f32, |acc, v| acc.max(v.abs()));
    if max_abs == 0.0 {
        return (vec![0i8; values.len()], 1.0);
    }
    let scale = max_abs / 127.0;
    let q = values
        .iter()
        .map(|v| (v / scale).round().clamp(-127.0, 127.0) as i8)
        .collect();
    (q, scale)
}

/// Dot product of two linearly-quantized INT8 vectors, descaled back to
/// the original FP32 magnitude.
pub fn int8_dot(a: &[i8], a_scale: f32, b: &[i8], b_scale: f32) -> f32 {
    let raw: i32 = a.iter().zip(b).map(|(x, y)| *x as i32 * *y as i32).sum();
    raw as f32 * a_scale * b_scale
}

/// Hamming distance between two equal-length packed-bit vectors (lower
/// is more similar).
pub fn hamming_distance(a: &[u8], b: &[u8]) -> u32 {
    a.iter().zip(b).map(|(x, y)| (x ^ y).count_ones()).sum()
}

/// MRL prefix + renormalize (spec §188: "MRL prefixes at dimensions 256
/// and 512 may be generated by truncating the trained representation...
/// and re-normalizing").
pub fn mrl_prefix_renormalized(values: &[f32], dim: usize) -> Vec<f32> {
    let mut prefix = values[..dim.min(values.len())].to_vec();
    l2_normalize(&mut prefix);
    prefix
}

impl FlatVectorStore {
    /// Embeds every `(id, text)` document through the real helper-model
    /// runtime and builds all reference controls. `max_input_tokens`
    /// bounds the encoder's input length: the reference forward pass's
    /// cost is dominated by input length until sequences reach several
    /// thousand tokens (see the module doc and the Phase 38
    /// qualification doc), so this keeps bulk-indexing tractable without
    /// changing model semantics.
    pub fn build(
        runtime: &PplxEmbedRuntime,
        documents: &[(String, String)],
        max_input_tokens: usize,
    ) -> Result<Self> {
        let mut records = Vec::with_capacity(documents.len());
        for (id, text) in documents {
            let embedding = runtime.embed_with_input_budget(text, None, Some(max_input_tokens))?;
            let mut fp32 = embedding.fp32;
            l2_normalize(&mut fp32);
            let (int8, int8_scale) = quantize_int8_linear(&fp32);
            records.push(FlatRecord {
                id: id.clone(),
                fp32,
                int8,
                int8_scale,
                binary_packed: embedding.ubinary,
            });
        }
        Ok(Self { records })
    }

    /// Exact FP32 cosine search (vectors are pre-normalized, so dot
    /// product *is* cosine similarity). Returns `(record_index, score)`
    /// sorted descending by score, top `k`.
    pub fn search_fp32(&self, query: &[f32], k: usize) -> Vec<(usize, f32)> {
        let mut scored: Vec<(usize, f32)> = self
            .records
            .iter()
            .enumerate()
            .map(|(i, r)| {
                let dot: f32 = r.fp32.iter().zip(query).map(|(a, b)| a * b).sum();
                (i, dot)
            })
            .collect();
        scored.sort_by(|a, b| b.1.total_cmp(&a.1));
        scored.truncate(k);
        scored
    }

    pub fn search_int8(&self, query: &[i8], query_scale: f32, k: usize) -> Vec<(usize, f32)> {
        let mut scored: Vec<(usize, f32)> = self
            .records
            .iter()
            .enumerate()
            .map(|(i, r)| (i, int8_dot(&r.int8, r.int8_scale, query, query_scale)))
            .collect();
        scored.sort_by(|a, b| b.1.total_cmp(&a.1));
        scored.truncate(k);
        scored
    }

    pub fn search_binary(&self, query_packed: &[u8], k: usize) -> Vec<(usize, u32)> {
        let mut scored: Vec<(usize, u32)> = self
            .records
            .iter()
            .enumerate()
            .map(|(i, r)| (i, hamming_distance(&r.binary_packed, query_packed)))
            .collect();
        scored.sort_by_key(|(_, distance)| *distance);
        scored.truncate(k);
        scored
    }
}

/// `|top-k(candidate) ∩ top-k(ground_truth)| / k` — the standard
/// recall@k used to compare a compact control against the FP32 gold
/// ranking (spec §189: "gold recall baseline for every approximate
/// index").
pub fn recall_at_k(candidate: &[usize], ground_truth: &[usize]) -> f32 {
    if ground_truth.is_empty() {
        return 1.0;
    }
    let hits = candidate
        .iter()
        .filter(|i| ground_truth.contains(i))
        .count();
    hits as f32 / ground_truth.len() as f32
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn l2_normalize_produces_unit_norm() {
        let mut v = vec![3.0, 4.0];
        l2_normalize(&mut v);
        let norm = v.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!((norm - 1.0).abs() < 1e-6);
    }

    #[test]
    fn int8_linear_quantization_round_trips_within_one_scale_step() {
        let values = vec![0.5, -0.25, 1.0, -1.0, 0.0];
        let (q, scale) = quantize_int8_linear(&values);
        for (original, quantized) in values.iter().zip(&q) {
            let dequant = *quantized as f32 * scale;
            assert!((dequant - original).abs() <= scale + 1e-6);
        }
    }

    #[test]
    fn hamming_distance_is_zero_for_identical_and_counts_differing_bits() {
        assert_eq!(hamming_distance(&[0xFF], &[0xFF]), 0);
        assert_eq!(hamming_distance(&[0b1111_0000], &[0b0000_1111]), 8);
    }

    #[test]
    fn fp32_search_ranks_the_closest_vector_first() {
        let store = FlatVectorStore {
            records: vec![
                FlatRecord {
                    id: "a".to_string(),
                    fp32: vec![1.0, 0.0],
                    int8: vec![],
                    int8_scale: 1.0,
                    binary_packed: vec![],
                },
                FlatRecord {
                    id: "b".to_string(),
                    fp32: vec![0.0, 1.0],
                    int8: vec![],
                    int8_scale: 1.0,
                    binary_packed: vec![],
                },
            ],
        };
        let results = store.search_fp32(&[0.9, 0.1], 2);
        assert_eq!(results[0].0, 0);
    }

    #[test]
    fn recall_at_k_counts_overlap() {
        assert_eq!(recall_at_k(&[1, 2, 3], &[1, 2, 3]), 1.0);
        assert_eq!(recall_at_k(&[1, 5, 9], &[1, 2, 3]), 1.0 / 3.0);
    }

    /// Real end-to-end qualification (spec §38's "preserve benchmark
    /// results forever"): builds the flat store over a real, semantically
    /// diverse slice of this crate's own source tree via the real Phase 37
    /// helper-model runtime, then measures INT8/binary recall@k against
    /// the FP32 gold ranking on real natural-language queries. Requires
    /// an already-converted pplx-embed `.tqf` (see the Phase 37
    /// qualification doc for how to produce one).
    #[test]
    #[ignore = "requires a converted pplx-embed .tqf checkpoint and tokenizer.json (Phase 37)"]
    fn real_repo_flat_index_recall_against_fp32_ground_truth() {
        use crate::ids::Bytes;
        use crate::memory::MemoryBroker;
        use std::path::Path;

        let tqf_path = std::env::var("TQF_PPLX_TQF").expect("set TQF_PPLX_TQF");
        let tokenizer_path = std::env::var("TQF_PPLX_TOKENIZER").expect("set TQF_PPLX_TOKENIZER");
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));

        let broker = MemoryBroker::new(Bytes(8 * 1024 * 1024 * 1024));
        let runtime =
            PplxEmbedRuntime::load(Path::new(&tqf_path), Path::new(&tokenizer_path), &broker)
                .expect("load runtime");

        // A deliberately semantically diverse real slice of this crate's
        // own source tree, not a synthetic fixture: memory/broker,
        // helper-model/embeddings, lexical retrieval, and expert-cache
        // concerns are all real, distinct clusters a good ranking should
        // separate.
        let relative_paths = [
            "src/memory/mod.rs",
            "src/helper_model/quantize.rs",
            "src/helper_model/runtime.rs",
            "src/retrieval/ignore.rs",
            "src/retrieval/classify.rs",
            "src/experts/policy.rs",
            "src/experts/prefetch.rs",
            "src/format/tqf/writer.rs",
            "src/context/tqattn/mod.rs",
            "src/context/prefix/mod.rs",
        ];
        let documents: Vec<(String, String)> = relative_paths
            .iter()
            .filter_map(|p| {
                let contents = std::fs::read_to_string(root.join(p)).ok()?;
                Some((p.to_string(), contents))
            })
            .collect();
        assert!(
            documents.len() >= 8,
            "expected most of the chosen real files to exist and be readable: {}",
            documents.len()
        );

        let max_input_tokens = 128;
        let started = std::time::Instant::now();
        let store =
            FlatVectorStore::build(&runtime, &documents, max_input_tokens).expect("build store");
        println!(
            "phase38_flat_build documents={} max_input_tokens={} elapsed_ms={}",
            store.records.len(),
            max_input_tokens,
            started.elapsed().as_millis()
        );

        // Optionally persist the real computed FP32 vectors so later
        // phases (Phase 39's TQVec candidate benchmark) can reuse this
        // corpus without re-running the expensive reference forward pass
        // — same "recapture the trace, replay offline" precedent as the
        // committed `raw-a-128-route-trace.json` fixture.
        if let Ok(dump_path) = std::env::var("TQF_PPLX_FLAT_CORPUS_DUMP") {
            let dump: Vec<serde_json::Value> = store
                .records
                .iter()
                .map(|r| serde_json::json!({"id": r.id, "fp32": r.fp32}))
                .collect();
            std::fs::write(
                &dump_path,
                serde_json::to_vec(&serde_json::json!({"documents": dump})).unwrap(),
            )
            .expect("write corpus dump");
            println!("phase38_corpus_dump path={dump_path}");
        }

        let queries = [
            (
                "how does the memory broker account for reserved bytes per owner",
                "src/memory/mod.rs",
            ),
            (
                "int8 and binary quantization of a pooled sentence embedding",
                "src/helper_model/quantize.rs",
            ),
            (
                "gitignore glob pattern matching for a repository file scanner",
                "src/retrieval/ignore.rs",
            ),
            (
                "eviction policy for a cache of mixture of experts weights",
                "src/experts/policy.rs",
            ),
        ];

        let k = 5;
        let mut int8_recalls = Vec::new();
        let mut binary_recalls = Vec::new();
        let mut query_dump: Vec<serde_json::Value> = Vec::new();
        for (query_text, expected_top_id) in queries {
            let query_embedding = runtime
                .embed_with_input_budget(query_text, None, Some(max_input_tokens))
                .expect("embed query");
            let mut query_fp32 = query_embedding.fp32.clone();
            l2_normalize(&mut query_fp32);
            let (query_int8, query_int8_scale) = quantize_int8_linear(&query_fp32);

            let fp32_hits = store.search_fp32(&query_fp32, k);
            let ground_truth: Vec<usize> = fp32_hits.iter().map(|(i, _)| *i).collect();

            let int8_hits = store.search_int8(&query_int8, query_int8_scale, k);
            let int8_ids: Vec<usize> = int8_hits.iter().map(|(i, _)| *i).collect();
            let int8_recall = recall_at_k(&int8_ids, &ground_truth);
            int8_recalls.push(int8_recall);

            let binary_hits = store.search_binary(&query_embedding.ubinary, k);
            let binary_ids: Vec<usize> = binary_hits.iter().map(|(i, _)| *i).collect();
            let binary_recall = recall_at_k(&binary_ids, &ground_truth);
            binary_recalls.push(binary_recall);

            let top_id = &store.records[fp32_hits[0].0].id;
            println!(
                "phase38_query {query_text:?} fp32_top1={top_id:?} expected_contains={} int8_recall@{k}={int8_recall} binary_recall@{k}={binary_recall}",
                top_id.contains(expected_top_id.trim_start_matches("src/"))
                    || top_id == expected_top_id
            );
            query_dump.push(serde_json::json!({
                "text": query_text,
                "fp32": query_fp32,
                "fp32_ground_truth_top_k": ground_truth,
            }));
        }

        if let Ok(dump_path) = std::env::var("TQF_PPLX_FLAT_QUERY_DUMP") {
            std::fs::write(
                &dump_path,
                serde_json::to_vec(&serde_json::json!({"queries": query_dump})).unwrap(),
            )
            .expect("write query dump");
            println!("phase38_query_dump path={dump_path}");
        }

        let mean_int8_recall = int8_recalls.iter().sum::<f32>() / int8_recalls.len() as f32;
        let mean_binary_recall = binary_recalls.iter().sum::<f32>() / binary_recalls.len() as f32;
        println!(
            "phase38_summary mean_int8_recall@{k}={mean_int8_recall} mean_binary_recall@{k}={mean_binary_recall}"
        );

        assert!(
            mean_int8_recall >= 0.8,
            "expected linear INT8 to closely track the FP32 gold ranking: {mean_int8_recall}"
        );
    }
}
